---
title: "Week-12_Model Diagnostics"
output: html_document
Author: "Gayathri Mutyala"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Checking the sample Assumptions

```{r echo=TRUE, message=FALSE, warning=FALSE}
sim_1 = function(sample_size = 500) {
  x = runif(n = sample_size) * 5
  y = 3 + 5 * x + rnorm(n = sample_size, mean = 0, sd = 1)
  data.frame(x, y)
}

sim_2 = function(sample_size = 500) {
  x = runif(n = sample_size) * 5
  y = 3 + 5 * x + rnorm(n = sample_size, mean = 0, sd = x)
  data.frame(x, y)
}

```

#Plotting fittes versus residual plot in R

```{r echo=TRUE, message=FALSE, warning=FALSE}
set.seed(42)
sim_data_1 = sim_1()
head(sim_data_1)

```
#Scatter plots of models


```{r echo=TRUE, message=FALSE, warning=FALSE}
plot(y ~ x, data = sim_data_1, col = "grey", pch = 20,
     main = "Data from Model 1")
fit_1 = lm(y ~ x, data = sim_data_1)
abline(fit_1, col = "darkorange", lwd = 3)


```



```{r echo=TRUE, message=FALSE, warning=FALSE}
plot(fitted(fit_1), resid(fit_1), col = "grey", pch = 20,
     xlab = "Fitted", ylab = "Residuals", main = "Data from Model 1")
abline(h = 0, col = "darkorange", lwd = 2)


```



```{r echo=TRUE, message=FALSE, warning=FALSE}
set.seed(42)
sim_data_2 = sim_2()
fit_2 = lm(y ~ x, data = sim_data_2)
plot(y ~ x, data = sim_data_2, col = "grey", pch = 20,
     main = "Data from Model 2")
abline(fit_2, col = "darkorange", lwd = 3)

```

# Breusch-Pagan Test for both the models

```{r echo=TRUE, message=FALSE, warning=FALSE}

#install.packages("lmtest")
library(lmtest)
bptest(fit_1)
bptest(fit_2)


```

#Plotting Histograms

```{r echo=TRUE, message=FALSE, warning=FALSE}

par(mfrow = c(1, 3))
hist(resid(fit_1),
     xlab   = "Residuals",
     main   = "Histogram of Residuals, fit_1",
     col    = "darkorange",
     border = "dodgerblue",
     breaks = 20)
hist(resid(fit_2),
     xlab   = "Residuals",
     main   = "Histogram of Residuals, fit_2",
     col    = "darkorange",
     border = "dodgerblue",
     breaks = 20)

```

#Plotting QQ plots
```{r echo=TRUE, message=FALSE, warning=FALSE}
qqnorm(resid(fit_1), main = "Normal Q-Q Plot, fit_1", col = "darkgrey")
qqline(resid(fit_1), col = "dodgerblue", lwd = 2)


qqnorm(resid(fit_2), main = "Normal Q-Q Plot, fit_2", col = "darkgrey")
qqline(resid(fit_2), col = "dodgerblue", lwd = 2)

```

#Shapiro-Wilk test for NOrmality Check

```{r echo=TRUE, message=FALSE, warning=FALSE}
set.seed(42)
shapiro.test(rnorm(25))
shapiro.test(rexp(25))
shapiro.test(resid(fit_1))
shapiro.test(resid(fit_2))
```
